[llm]
provider = "openai"
model = "gpt-4o"
temperature = 0.2

[search]
sources = ["openalex", "arxiv", "pubmed"]
year_min = 2018
language = ["en", "fi"]

[screening]
use_asreview = true
recall_target = 0.9

[pdf]
dir = "data/pdfs"
audit_log = "data/logs/pdf_audit.csv"
timeout_s = 30
retries = 2
throttle_ms = 200
grobid_url = "http://localhost:8070"

[unpaywall]
email = ""

[rag]
vector_store = "chroma"
chunk_size = 1200
chunk_overlap = 200

[report]
engine = "quarto"
csl = "vancouver.csl"

[run]
provider = "gemini"
model = "text-embedding-004|gemini-1.5-pro"
budget_usd = 3.0
max_iterations = 2
top_k = 6
bm25_k = 20
questions = ["Mikä on...?", "Miten ...?"]
require_sources = 2
enforce_pages = true
