[llm]
provider = "openai"
model = "gpt-4o"
temperature = 0.2

[search]
sources = ["openalex", "arxiv", "pubmed"]
year_min = 2018
language = ["en", "fi"]

[screening]
use_asreview = true
recall_target = 0.9

[pdf]
dir = "data/pdfs"
audit_log = "data/logs/pdf_audit.csv"
timeout_s = 30
retries = 2
throttle_ms = 200
grobid_url = "http://localhost:8070"

[unpaywall]
email = ""

[rag]
vector_store = "chroma"
chunk_size = 1200
chunk_overlap = 200

[report]
engine = "quarto"
csl = "vancouver.csl"
