name: Audit
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  audit:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pipx install uv
      - name: Create venv and install dev deps
        shell: pwsh
        run: |
          uv venv
          .\.venv\Scripts\Activate.ps1
          uv pip install ruff mypy pytest
          uv pip install -e .
      - name: Run audit script
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          PowerShell -ExecutionPolicy Bypass -File .\scripts\audit.ps1
