name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -r requirements.txt || true
          uv pip install pytest mypy ruff
          uv pip install -e .


      - name: Check PR title (Conventional Commits)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          PR_NUM="${{ github.event.pull_request.number }}"
          # Hae tuore otsikko; jos gh ei toimi (esim. fork-PR), käytä event-payloadia
          msg="$(gh pr view "$PR_NUM" --json title -q .title || jq -r '.pull_request.title // ""' "$GITHUB_EVENT_PATH")"
          echo "PR title: $msg"
          # tyyppi [scope optional] : viesti  (vaatii tekstin kolonin jälkeen)
          if echo "$msg" | grep -Eiq '^(feat|fix|chore|docs|ci|refactor|test|perf)(\([^)]+\))?: .+'; then
            echo ok
          else
            echo "PR otsikon tulee noudattaa muotoa: tyyppi(scope): viesti"
            exit 1
          fi

      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check .
          mypy --ignore-missing-imports .

      - name: Test
        run: |
          . .venv/bin/activate
          pytest -q
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t tutkija:ci .
