name: E2E Nightly
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pipx install uv
      - name: Setup venv
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e .
          uv pip install ruff mypy pytest
      - name: Smoke, la hello
        run: |
          . .venv/bin/activate
          la hello | head -n 3
